### ISSUE TITLE
云端部署

### ISSUE THREAD

**Issue by niezie** [MelodyYuuka/NeteaseCloudMusic-Audio-Recognize#2]
请问大佬，为什么云端部署无效呢

**Comment by MelodyYuuka** [comment]
云端部署是指？
详细描述一下问题

**Comment by niezie** [comment]
[root@hecs-365171 FindMusic]# node test
Module loading: /FindMusic/afp.wasm
/FindMusic/sandbox.bundle.js:43
                        throw t
                        ^

Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
    at n (/FindMusic/sandbox.bundle.js:1922:23)
    at c (/FindMusic/sandbox.bundle.js:1939:57)
    at Object.start (/FindMusic/sandbox.bundle.js:1965:38)
    at /FindMusic/sandbox.bundle.js:2019:28
    at new Promise (<anonymous>)
    at NeteaseRecordArrayToBase64 (/FindMusic/sandbox.bundle.js:2003:12)
    at Object.encode (/FindMusic/sandbox.bundle.js:2061:16)
    at async /FindMusic/test.js:14:19
[root@hecs-365171 FindMusic]# python3 match_music.py 
Traceback (most recent call last):
  File "match_music.py", line 6, in <module>
    from javascript import require
ImportError: cannot import name 'require'

**Comment by niezie** [comment]
我运行python代码显示没办法导入require，用node运行也不行，麻烦你大佬

**Comment by MelodyYuuka** [comment]
检查一下 nodejs 和 python 依赖是否完整安装
- 我这里本机 Node.js 版本为 v18.14.0
- python 版本为 python3.11
  - JavaScript 子依赖版本为 1!1.1.0

我这边最近比较忙可能没法帮太多，可以根据报错信息找一下解决方案

**Comment by niezie** [comment]
感谢大佬，我自己再试试
